# Generated by Django 6.0.4 on 2026-05-07 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_region_productavailability'),
        ('user', '0002_alter_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW_PRODUCT', 'View Product'), ('SEE_QUANTITY', 'See Quantity'), ('EDIT_PRICE', 'Edit Price')], max_length=20)),
                ('is_allowed', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
