# Generated by Django 6.0.4 on 2026-05-07 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_region_productavailability'),
        ('user', '0003_userproductpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductpermission',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='product.region'),
        ),
        migrations.AlterField(
            model_name='userproductpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userproductpermission',
            constraint=models.UniqueConstraint(fields=('user', 'region', 'permission'), name='unique_user_region_permission'),
        ),
    ]
