# Generated by Django 6.0.4 on 2026-05-07 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(choices=[('KG', 'Kilogram'), ('TON', 'Ton'), ('LITRE', 'Litre'), ('PIECE', 'Piece'), ('BOTTLE', 'Bottle'), ('PACK', 'Pack'), ('SET', 'Set'), ('BAG', 'Bag'), ('CAN', 'Can'), ('BOX', 'Box'), ('CARTON', 'Carton'), ('METER', 'Meter'), ('SQUARE_METER', 'Square Meter'), ('CUBIC_METER', 'Cubic Meter')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
