# Generated by Django 6.0.4 on 2026-05-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_region_productavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productavailability',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availabilities', to='product.region'),
        ),
        migrations.AddConstraint(
            model_name='productavailability',
            constraint=models.UniqueConstraint(fields=('product', 'region'), name='unique_product_region'),
        ),
    ]
